### ISSUE TITLE
Not able to run virtuoso with freebase-qa

### ISSUE THREAD

**Issue by SaminSid** [ad-freiburg/aqqu#1]
I'm not able to run virtuoso with freebase-qa although it is running with virtuoso empty db. Do I need to make changes in some config files?

**Comment by elmarhaussmann** [comment]
Can you provide an error message? What happens if you run "make
start-virtuoso"?
I am on a plane for the next 30 hours and will look into it when back home.

**Comment by SaminSid** [comment]
It seems to have worked by updating .ini file to point to freebase-qa db. Thanks
